export const LOADING = "LOADING";
export const SET_CITY = "SEARCH_WEATHER";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAIL = "FETCH_WEATHER_FAIL";
export const FETCH_WEATHER = "FETCH_WEATHER";
